name: Upload to S3

on:
  release:
    types: [created]

jobs:
  deploy:
    name: Upload
    runs-on: ubuntu-18.04
    environment: production

    steps:
      - uses: actions/checkout@v2

      - name: Inject env
        run: |
          touch .env
          echo "${{ secrets.ENV_FILE }}" >> .env

      - name: Zip Artifacts
        run: zip pickk-server-cron.zip -r . -x './.github/*' -x './.git/*' -x './node_modules/*'

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp ./pickk-server-cron.zip s3://pickk-server-cron-zip
